# -*- coding: utf-8 -*-
# Spalten-Referenz: (Tabelle, Spalte, deutsch, englisch, sicher)
# sicher=True: aus Daten/Verwendung im Editor belegt; False: aus dem Namen abgeleitet ("vermutet").
COLS = [
 ("*","ID",True,"Nummer der Zeile (eindeutig). Andere Tabellen verweisen darüber.","Number of the row (unique). Other tables refer to it."),
 ("*","InxName",True,"Interner Textschlüssel. Andere Tabellen verweisen darüber; vorhandene nicht umbenennen.","Internal text key. Other tables refer to it; do not rename existing ones."),
 ("*","Name",True,"Anzeigename im Spiel.","Display name in game."),
 ("MobInfo","Level",True,"Level des Mobs/NPCs.","Level of the mob/NPC."),
 ("MobInfo","MaxHP",True,"Maximale Lebenspunkte.","Maximum hit points."),
 ("MobInfo","WalkSpeed",True,"Gehgeschwindigkeit.","Walking speed."),
 ("MobInfo","RunSpeed",True,"Laufgeschwindigkeit.","Running speed."),
 ("MobInfo","IsNPC",True,"1 = NPC, 0 = Monster.","1 = NPC, 0 = monster."),
 ("MobInfo","Size",False,"Größe des Modells (1000 = normal).","Size of the model (1000 = normal)."),
 ("MobInfo","WeaponType",False,"Art der geführten Waffe.","Kind of wielded weapon."),
 ("MobInfo","ArmorType",False,"Art der Rüstung.","Kind of armor."),
 ("MobInfo","GradeType",False,"Rang/Klasse des Mobs (normal, Elite, Boss ...).","Rank/class of the mob (normal, elite, boss ...)."),
 ("MobInfo","IsPlayerSide",False,"Steht auf der Seite der Spieler.","Is on the players' side."),
 ("MobInfo","AbsoluteSize",False,"Absolute Größe (ohne Skalierung).","Absolute size (without scaling)."),
 ("MobInfoServer","MonEXP",True,"Erfahrungspunkte beim Töten (XP Rate Editor ändert diese Spalte).","Experience for a kill (the XP Rate Editor changes this column)."),
 ("MobInfoServer","EXPRange",True,"Streubereich der Erfahrung (wird vom XP Rate Editor mitskaliert).","Spread of the experience (scaled together by the XP Rate Editor)."),
 ("MobInfoServer","AC",False,"Rüstungswert.","Armor value."),
 ("MobInfoServer","MR",False,"Magieresistenz.","Magic resistance."),
 ("MobInfoServer","TB",False,"Blockchance/Ausweichwert (TB).","Block/evade value (TB)."),
 ("MobInfoServer","MB",False,"Magischer Block (MB).","Magic block (MB)."),
 ("MobInfoServer","Visible",False,"Sichtbar für Spieler.","Visible to players."),
 ("MobInfoServer","EnemyDetectType",False,"Art der Gegnererkennung.","Kind of enemy detection."),
 ("MobInfoServer","DetectCha",False,"Erkennungs-/Aggro-Reichweite.","Detection/aggro range."),
 ("MobInfoServer","IsRoaming",False,"1 = wandert umher.","1 = roams around."),
 ("MobInfoServer","RoamingNumber",False,"Anzahl der Wanderziele.","Number of roaming targets."),
 ("MobInfoServer","RoamingDistance",False,"Wanderentfernung.","Roaming distance."),
 ("MobInfoServer","RoamingRestTime",False,"Ruhezeit zwischen Wanderungen.","Rest time between roams."),
 ("MobInfoServer","Str",False,"Attribut Stärke.","Attribute strength."),
 ("MobInfoServer","Dex",False,"Attribut Geschick.","Attribute dexterity."),
 ("MobInfoServer","Con",False,"Attribut Konstitution.","Attribute constitution."),
 ("MobInfoServer","Int",False,"Attribut Intelligenz.","Attribute intelligence."),
 ("MobInfoServer","Men",False,"Attribut Mentalität.","Attribute mentality."),
 ("MobInfoServer","MobKillInx",False,"Zähl-/Drop-Gruppe beim Töten.","Kill counter/drop group."),
 ("MobInfoServer","Rank",False,"Rang des Mobs.","Rank of the mob."),
 ("MobInfoServer","MaxSP",False,"Maximale SP.","Maximum SP."),
 ("MobViewInfo","FileName",True,"Modell des Mobs/NPCs: reschar/<FileName>/<FileName>.nif (oder ein anderer res*-Ordner).","Model of the mob/NPC: reschar/<FileName>/<FileName>.nif (or another res* folder)."),
 ("MobViewInfo","Texture",False,"Alternative Textur des Modells.","Alternative texture of the model."),
 ("MobViewInfo","NpcViewIndex",True,"0 = normales Modell (FileName). Sonst Verweis auf NPCViewInfo.TypeIndex (Spieler-Aussehen).","0 = normal model (FileName). Otherwise reference to NPCViewInfo.TypeIndex (player look)."),
 ("MobViewInfo","MobPortrait",False,"Porträtbild im Spiel.","Portrait image in game."),
 ("MobViewInfo","MiniMapIcon",False,"Symbol auf der Minikarte.","Icon on the minimap."),
 ("MobViewInfo","BoundingBox",False,"Größe des Auswahlkörpers.","Size of the selection volume."),
 ("MobViewInfo","AttackType",False,"Art des Angriffs (Nahkampf/Fernkampf).","Kind of attack (melee/ranged)."),
 ("MobViewInfo","ShotEffect",False,"Geschoss-Effekt bei Fernangriff.","Projectile effect for ranged attacks."),
 ("NPCViewInfo","TypeIndex",True,"Nummer des Spieler-Aussehens (Ziel von MobViewInfo.NpcViewIndex).","Number of the player look (target of MobViewInfo.NpcViewIndex)."),
 ("NPCViewInfo","Class",True,"Klasse 0-5: 0 Fighter, 1 Archer, 2 Cleric, 3 Mage, 4 Joker, 5 Sentinel.","Class 0-5: 0 fighter, 1 archer, 2 cleric, 3 mage, 4 joker, 5 sentinel."),
 ("NPCViewInfo","Gender",False,"Geschlecht (1 männlich, 0 weiblich - aus ChrCreateEquip abgeleitet).","Gender (1 male, 0 female - derived from ChrCreateEquip)."),
 ("NPCViewInfo","FaceShape",True,"Gesichtsform (Face00N.nif).","Face shape (Face00N.nif)."),
 ("NPCViewInfo","HairType",True,"Frisur (HairInfo-ID).","Hairstyle (HairInfo ID)."),
 ("NPCViewInfo","HairColor",False,"Haarfarbe.","Hair color."),
 ("NPCViewInfo","BaseActionCode",False,"Standard-Animation im Stand.","Standard idle animation."),
 ("NPCViewInfo","PeriodActionCode",False,"Gelegentliche Zusatz-Animation.","Occasional extra animation."),
 ("NPCViewInfo","ActionDelayTime",False,"Pause zwischen Zusatz-Animationen.","Pause between extra animations."),
 ("NPCViewInfo","bUseEventAction",False,"Ereignis-Animationen verwenden.","Use event animations."),
 ("NPCViewInfo","Equ_RightHand",True,"Item (InxName) in der rechten Hand.","Item (InxName) in the right hand."),
 ("NPCViewInfo","Equ_LeftHand",True,"Item (InxName) in der linken Hand (Schild).","Item (InxName) in the left hand (shield)."),
 ("NPCViewInfo","Equ_Body",True,"Rüstungsteil Körper (Item-InxName).","Body armor piece (item InxName)."),
 ("NPCViewInfo","Equ_Leg",True,"Rüstungsteil Beine (Item-InxName).","Leg armor piece (item InxName)."),
 ("NPCViewInfo","Equ_Shoes",True,"Rüstungsteil Schuhe (Item-InxName).","Shoe armor piece (item InxName)."),
 ("NpcDialogData","MobIDX",True,"InxName des NPCs, zu dem das Gespräch gehört.","InxName of the NPC the conversation belongs to."),
 ("NpcDialogData","FaceCutFile",False,"Porträtbild im Gesprächsfenster.","Portrait image in the conversation window."),
 ("NpcDialogData","Dialog",True,"Gesprächstext: Begrüßung und Antwort-Knöpfe (im Dialog-Editor bearbeitbar).","Conversation text: greeting and answer buttons (editable in the dialog editor)."),
 ("ItemInfo","BuyPrice",True,"Kaufpreis beim Händler (Buy & Sell Editor ändert diese Spalte).","Buy price at the merchant (the Buy & Sell Editor changes this column)."),
 ("ItemInfo","SellPrice",True,"Verkaufspreis an den Händler (Buy & Sell Editor).","Sell price to the merchant (Buy & Sell Editor)."),
 ("ItemInfo","MinWC",False,"Minimaler Waffenschaden.","Minimum weapon damage."),
 ("ItemInfo","MaxWC",False,"Maximaler Waffenschaden.","Maximum weapon damage."),
 ("ItemInfo","MinMA",False,"Minimaler magischer Schaden.","Minimum magic damage."),
 ("ItemInfo","MaxMA",False,"Maximaler magischer Schaden.","Maximum magic damage."),
 ("ItemInfo","AC",False,"Rüstungswert.","Armor value."),
 ("ItemInfo","MR",False,"Magieresistenz.","Magic resistance."),
 ("ItemInfo","DemandLv",False,"Benötigtes Charakterlevel.","Required character level."),
 ("ItemInfo","MaxLot",False,"Maximale Stapelgröße.","Maximum stack size."),
 ("ItemInfo","Equip",False,"Ausrüstungs-Slot (Aufzählung).","Equipment slot (enum)."),
 ("ItemInfo","UseClass",False,"Klassen, die das Item nutzen dürfen (Bitmaske).","Classes allowed to use the item (bitmask)."),
 ("ItemInfo","MarketIndex",False,"Markt-Kategorie; 'Skill' kennzeichnet Skillbücher.","Market category; 'Skill' marks skill books."),
 ("ItemInfo","AtkSpeed",False,"Angriffsgeschwindigkeit der Waffe.","Attack speed of the weapon."),
 ("ItemInfo","TwoHand",False,"1 = Zweihandwaffe.","1 = two-handed weapon."),
 ("ItemViewInfo","IconFile",True,"Icon-Bilddatei des Items.","Icon image file of the item."),
 ("ItemViewInfo","IconIndex",True,"Position des Icons in der Bilddatei.","Position of the icon in the image file."),
 ("ItemViewInfo","LinkFile",True,"Modell einer Waffe/eines Schilds: resitem/<LinkFile>.nif.","Model of a weapon/shield: resitem/<LinkFile>.nif."),
 ("ItemViewInfo","TextureFile",True,"Rüstungstextur im Klassenordner (reschar/<Klasse>-<m|f>/<TextureFile>.dds).","Armor texture in the class folder (reschar/<class>-<m|f>/<TextureFile>.dds)."),
 ("ItemViewInfo","MSetNo",True,"Nummer des Rüstungs-Modells für männliche Charaktere (setNNN.nif).","Number of the armor model for male characters (setNNN.nif)."),
 ("ItemViewInfo","FSetNo",True,"Nummer des Rüstungs-Modells für weibliche Charaktere (setNNN.nif).","Number of the armor model for female characters (setNNN.nif)."),
 ("ItemViewInfo","EquipType",False,"Art der Ausrüstung für die Darstellung (Aufzählung).","Kind of equipment for the display (enum)."),
 ("ItemViewInfo","Descript",False,"Beschreibungstext.","Description text."),
 ("MapInfo","MapName",False,"Interner Kartenname (Ordner-/Dateiname).","Internal map name (folder/file name)."),
 ("MapInfo","RegenX",False,"Start-/Wiederbelebungspunkt X.","Start/respawn point X."),
 ("MapInfo","RegenY",False,"Start-/Wiederbelebungspunkt Y (Welt-Z).","Start/respawn point Y (world Z)."),
 ("MapInfo","MapFolderName",False,"Ordnername der Karte im Client.","Folder name of the map in the client."),
 ("MapInfo","InSide",False,"1 = Innenraum-Karte.","1 = indoor map."),
 ("MapInfo","Sight",False,"Sichtweite.","View distance."),
 ("MobWeapon","Skill",False,"Skill, den diese Waffenzeile einsetzt.","Skill this weapon row uses."),
 ("MobWeapon","MinWC",False,"Minimaler Schaden.","Minimum damage."),
 ("MobWeapon","MaxWC",False,"Maximaler Schaden.","Maximum damage."),
 ("MobWeapon","Range",False,"Reichweite.","Range."),
 ("MobWeapon","AtkSpd",False,"Angriffsgeschwindigkeit.","Attack speed."),
 ("MobWeapon","SwingTime",False,"Dauer der Angriffsbewegung (ms).","Duration of the attack motion (ms)."),
 ("MobWeapon","HitTime",False,"Trefferzeitpunkt in der Animation (ms).","Hit moment within the animation (ms)."),
 ("ShineNPC","MobName",True,"InxName des NPCs (Verweis auf MobInfo).","InxName of the NPC (reference to MobInfo)."),
 ("ShineNPC","Map",True,"Karte, auf der der NPC steht.","Map the NPC stands on."),
 ("ShineNPC","Coord-X",True,"Welt-X (Ost).","World X (east)."),
 ("ShineNPC","Coord-Y",True,"Welt-Z (Nord).","World Z (north)."),
 ("ShineNPC","Direct",True,"Blickrichtung in Grad.","Facing direction in degrees."),
 ("ShineNPC","NPCMenu",False,"Menü-Kennzeichen (meist 1).","Menu flag (usually 1)."),
 ("ShineNPC","Role",True,"Rolle: QuestNpc, Merchant, Guard, NPCMenu, StoreManager, Gate.","Role: QuestNpc, Merchant, Guard, NPCMenu, StoreManager, Gate."),
 ("ShineNPC","RoleArg0",True,"Rollenargument (z.B. Merchant + Item/Weapon/WeaponTitle/Skill/Guild).","Role argument (e.g. Merchant + Item/Weapon/WeaponTitle/Skill/Guild)."),
]
