# -*- coding: utf-8 -*-
# Tooltips: Beschriftung (mit oder ohne ##Suffix) -> (Deutsch, Englisch). Vorrang hat die Beschriftung MIT Suffix.
TIPS = {
 # ---- Projekt / Karte laden und speichern
 "Asset-Ordner wählen...": ("Ordner mit den Modellen und Texturen (Client) wählen, aus dem NIF-Modelle und Texturen geladen werden.", "Choose the folder with the models and textures (client) from which NIF models and textures are loaded."),
 "Karte-.ini": ("Pfad der Karten-.ini (z.B. resmap/field/Rou/Rou.ini). Sie beschreibt Größe, Texturschichten und Dateien der Karte.", "Path of the map .ini (e.g. resmap/field/Rou/Rou.ini). It describes size, texture layers and files of the map."),
 "Karte öffnen": ("Liest die Karte (Höhe, Texturen, Begehbarkeit, Objekte) aus der angegebenen .ini.", "Reads the map (height, textures, walkability, objects) from the given .ini."),
 "Ausgabeverzeichnis": ("Ordner, in den 'Karte speichern' die Kartendateien schreibt.", "Folder into which 'Save map' writes the map files."),
 "Wählen...": ("Ordner über einen Dialog auswählen.", "Choose a folder via a dialog."),
 "Kartenname": ("Name der Karte = Dateiname der geschriebenen Dateien (ohne Endung).", "Name of the map = file name of the written files (without extension)."),
 "Karte speichern": ("Schreibt die Karte im Originalformat (Höhe, Texturen, Block&Walk, Objekte) in das Ausgabeverzeichnis.", "Writes the map in its original format (height, textures, Block&Walk, objects) to the output directory."),
 "Neu (257x257)": ("Legt eine neue, flache Karte mit 257x257 Höhenpunkten an.", "Creates a new flat map with 257x257 height points."),
 "Laden (.tshm)": ("Lädt die Höhenkarte im eigenen Format .tshm.", "Loads the heightmap in the own .tshm format."),
 "Speichern (.tshm)": ("Speichert die Höhenkarte im eigenen Format .tshm.", "Saves the heightmap in the own .tshm format."),
 "Pfad##legacy": ("Pfad der Original-Höhendatei (.HTD).", "Path of the original height file (.HTD)."),
 "Breite (aus .ini)": ("Anzahl der Höhenpunkte in X-Richtung (steht in der Karten-.ini).", "Number of height points in X direction (found in the map .ini)."),
 "Höhe (aus .ini)": ("Anzahl der Höhenpunkte in Z-Richtung (steht in der Karten-.ini).", "Number of height points in Z direction (found in the map .ini)."),
 "Blockbreite": ("Größe eines Höhenblocks in X (Welteinheiten, meist 50).", "Size of a height block in X (world units, usually 50)."),
 "Blockhöhe": ("Größe eines Höhenblocks in Z (Welteinheiten, meist 50).", "Size of a height block in Z (world units, usually 50)."),
 "Importieren##htd": ("Liest eine Höhendatei (.HTD) mit den obigen Maßen.", "Reads a height file (.HTD) with the dimensions above."),
 "Exportieren##htd": ("Schreibt die Höhenkarte als Original-.HTD.", "Writes the heightmap as an original .HTD."),
 "Laden (.tstex)": ("Lädt die Texturschichten im eigenen Format .tstex.", "Loads the texture layers in the own .tstex format."),
 "Speichern (.tstex)": ("Speichert die Texturschichten im eigenen Format .tstex.", "Saves the texture layers in the own .tstex format."),
 "ini-Pfad##legacyTex": ("Karten-.ini, aus der die Texturschichten (mit Regionen) importiert werden.", "Map .ini from which the texture layers (with regions) are imported."),
 "Legacy-Set importieren": ("Importiert alle Texturschichten samt Blend-BMPs aus der .ini.", "Imports all texture layers including blend BMPs from the .ini."),
 "Export-Verzeichnis##legacyTex": ("Ordner, in den die Textur-Dateien (.ini und BMPs) exportiert werden.", "Folder to which the texture files (.ini and BMPs) are exported."),
 "Legacy-Set exportieren": ("Schreibt Texturschichten als .ini und Blend-BMPs im Originalformat.", "Writes texture layers as .ini and blend BMPs in the original format."),
 "Laden (.tswalk)": ("Lädt die Begehbarkeit im eigenen Format .tswalk.", "Loads the walkability in the own .tswalk format."),
 "Speichern (.tswalk)": ("Speichert die Begehbarkeit im eigenen Format .tswalk.", "Saves the walkability in the own .tswalk format."),
 "Pfad##walkLegacy": ("Pfad der Original-Begehbarkeitsdatei (.shbd).", "Path of the original walkability file (.shbd)."),
 "Breite##walkLegacy": ("Breite des Gitters in 16-Bit-Wörtern (je 16 Zellen).", "Grid width in 16-bit words (16 cells each)."),
 "Höhe##walkLegacy": ("Höhe des Gitters in Zeilen (= Zellen).", "Grid height in rows (= cells)."),
 "Importieren##shbd": ("Liest eine .shbd-Datei mit den obigen Maßen.", "Reads a .shbd file with the dimensions above."),
 "Exportieren##shbd": ("Schreibt die Begehbarkeit als Original-.shbd.", "Writes the walkability as an original .shbd."),
 "Laden (.tsobj)": ("Lädt die Objekte im eigenen Format .tsobj.", "Loads the objects in the own .tsobj format."),
 "Speichern (.tsobj)": ("Speichert die Objekte im eigenen Format .tsobj.", "Saves the objects in the own .tsobj format."),
 "Pfad##shmd": ("Pfad der Objektdatei (.shmd).", "Path of the object file (.shmd)."),
 "Importieren##shmd": ("Liest die Objektliste aus einer .shmd.", "Reads the object list from a .shmd."),
 "Exportieren##shmd": ("Schreibt die Objektliste als .shmd.", "Writes the object list as a .shmd."),
 "Pfad##idm": ("Pfad der Objekt-Indexdatei (.idm).", "Path of the object index file (.idm)."),
 "Importieren##idm": ("Liest die Objektindexdatei (.idm).", "Reads the object index file (.idm)."),
 "Exportieren##idm": ("Schreibt die Objektindexdatei (.idm).", "Writes the object index file (.idm)."),
 "Pfad##aid": ("Pfad der Objekt-Attributdatei (.aid).", "Path of the object attribute file (.aid)."),
 "Importieren##aid": ("Liest die Objekt-Attributdatei (.aid).", "Reads the object attribute file (.aid)."),
 "Exportieren##aid": ("Schreibt die Objekt-Attributdatei (.aid).", "Writes the object attribute file (.aid)."),
 "Erweitert (natives Format / Legacy Import-Export)": ("Einzelne Dateien getrennt importieren/exportieren und das eigene Format nutzen.", "Import/export single files separately and use the own format."),
 "Neu durchsuchen": ("Liest die Modell-/Textur-Bibliothek des Asset-Ordners erneut ein.", "Rescans the model/texture library of the asset folder."),
 # ---- Allgemein
 "Übernehmen": ("Wendet den eingegebenen Wert an. Ungültige Werte werden abgelehnt.", "Applies the entered value. Invalid values are rejected."),
 "Abbrechen": ("Verwirft die Eingabe.", "Discards the input."),
 "Schließen": ("Schließt dieses Fenster.", "Closes this window."),
 "Entfernen": ("Entfernt den gewählten Eintrag.", "Removes the selected entry."),
 "← Zurück": ("Zurück zur vorherigen Ebene.", "Back to the previous level."),
 "Speichern": ("Schreibt die geänderte Datei auf die Platte.", "Writes the modified file to disk."),
 # ---- SHN-Editor
 "CLIENT: SHN-Ordner einlesen": ("Liest alle SHN-Tabellen des Client-Ordners (ressystem) ein.", "Reads all SHN tables of the client folder (ressystem)."),
 "SERVER: SHN-Ordner einlesen": ("Liest alle SHN-Tabellen des Server-Ordners (9Data/Shine) ein.", "Reads all SHN tables of the server folder (9Data/Shine)."),
 "Einzelne SHN öffnen...": ("Öffnet eine einzelne SHN-Datei über einen Dateidialog.", "Opens a single SHN file via a file dialog."),
 "Datei": ("Dateiname oder Pfad einer SHN-Datei.", "File name or path of an SHN file."),
 "Pfad öffnen": ("Öffnet die SHN-Datei mit dem angegebenen Pfad.", "Opens the SHN file with the given path."),
 "Suche": ("Filtert die Tabellenzeilen nach dem eingegebenen Text.", "Filters the table rows by the entered text."),
 "Spalten durchsuchen": ("Die Suche prüft auch die Spaltennamen.", "The search also checks the column names."),
 "Werte durchsuchen": ("Die Suche prüft auch die Zellwerte.", "The search also checks the cell values."),
 "Zelle bearbeiten": ("Öffnet das Eingabefeld für die gewählte Zelle (oder Doppelklick auf die Zelle).", "Opens the input field for the selected cell (or double-click the cell)."),
 "+ Neue Zeile (in Familie propagieren)": ("Legt eine Zeile mit automatisch freier ID an - in dieser Tabelle und allen zugehörigen (z.B. ItemInfo + ItemViewInfo).", "Creates a row with an automatically free ID - in this table and all related ones (e.g. ItemInfo + ItemViewInfo)."),
 "Aufgabe": ("Wählt die Aufgabe; relevante Tabellen werden als Kandidaten gelb markiert.", "Chooses the task; relevant tables are marked yellow as candidates."),
 "% Änderung": ("Prozentwert, um den ALLE Zeilen der Spalte verändert werden (z.B. 10 = +10 %, -20 = -20 %).", "Percentage by which ALL rows of the column are changed (e.g. 10 = +10 %, -20 = -20 %)."),
 # ---- Quest
 "Monster-Ziele": ("Zu tötende Monster: aktiv, Mob-ID, Anzahl.", "Monsters to kill: active, mob ID, count."),
 "Item-Ziele": ("Zu sammelnde Items: aktiv, Item-ID, Anzahl.", "Items to collect: active, item ID, count."),
 "Drops": ("Items, die bestimmte Monster für diese Quest fallen lassen: Mob, Item, Menge, Rate.", "Items that certain monsters drop for this quest: mob, item, amount, rate."),
 "+ Drop hinzufügen": ("Fügt einen Drop-Eintrag hinzu (maximal 11).", "Adds a drop entry (maximum 11)."),
 "SAY-Text-ID nachschlagen": ("Gibt eine Text-ID aus einem SAY-Befehl ein und zeigt den Text aus QuestDialog.", "Enter a text ID from a SAY command and show the text from QuestDialog."),
 "QuestData.shn speichern": ("Schreibt alle Quests zurück in QuestData.shn (Server).", "Writes all quests back to QuestData.shn (server)."),
 "SmallButton:X": ("Entfernt diese Zeile.", "Removes this row."),
 "InputInt:X": ("X-Position in Welteinheiten (Ost).", "X position in world units (east)."),
 "InputInt:Y": ("Y-Position in Welteinheiten (Welt-Z, Nord).", "Y position in world units (world Z, north)."),
 "Zonenname": ("Name der Spawn-Zone (Gruppenname in MobRegen).", "Name of the spawn zone (group name in MobRegen)."),
 # ---- Portale
 "TownPortal.shn speichern": ("Schreibt die Stadtportal-Ziele (Client-Datei TownPortal.shn).", "Writes the town portal targets (client file TownPortal.shn)."),
 "RecallCoord.txt speichern": ("Schreibt die Schriftrollen-Ziele (Server-Datei RecallCoord.txt).", "Writes the scroll targets (server file RecallCoord.txt)."),
 "Mindestlevel": ("Charakterlevel, ab dem das Ziel im Menü erscheint.", "Character level from which the target appears in the menu."),
 "Menü-Gruppe": ("Gruppe/Sortierung des Ziels im Portal-Menü.", "Group/sorting of the target in the portal menu."),
 "Position per Klick im 2D-View setzen": ("Danach in die 2D-Ansicht klicken, um die Position zu setzen.", "Then click in the 2D view to set the position."),
 "TownPortal-Ziel hier hinzufügen": ("Legt ein neues Stadtportal-Ziel an.", "Creates a new town portal target."),
 "Verwerfen und neu laden": ("Verwirft alle ungespeicherten Portal-Änderungen und liest neu.", "Discards all unsaved portal changes and rereads."),
 # ---- Dialog / KI / Route
 "Event": ("Name des Ereignisses/Skripts, das der NPC ausführt.", "Name of the event/script the NPC runs."),
 "+ Wegpunkt hinzufügen": ("Fügt einen Punkt zur Patrouillenroute hinzu.", "Adds a point to the patrol route."),
 "+ Button hinzufügen": ("Fügt dem Dialog einen weiteren Antwort-Knopf hinzu.", "Adds another answer button to the dialog."),
 "Ordner wählen...##ressystem": ("Ordner ressystem des Clients manuell wählen (enthält NpcDialogData.shn).", "Choose the client's ressystem folder manually (contains NpcDialogData.shn)."),
 "Ordner wählen...##shinetextnpc": ("Ordner 9Data/Shine des Servers manuell wählen (enthält World/NPC.txt).", "Choose the server's 9Data/Shine folder manually (contains World/NPC.txt)."),
 "Ordner wählen...##shinetextmob": ("Ordner 9Data/Shine des Servers manuell wählen (enthält MobRegen).", "Choose the server's 9Data/Shine folder manually (contains MobRegen)."),
 # ---- Shop
 "Shop-Datei neu anlegen": ("Legt für diesen NPC eine neue NPCItemList-Datei mit einem leeren Tab an.", "Creates a new NPCItemList file with an empty tab for this NPC."),
 "^": ("Verschiebt diese Zeile nach oben.", "Moves this row up."),
 "v": ("Verschiebt diese Zeile nach unten.", "Moves this row down."),
 "x": ("Löscht diese Zeile (nur sichtbar, wenn 'Löschen freigeben' gesetzt ist).", "Deletes this row (only visible when 'Allow delete' is ticked)."),
 "+ Zeile": ("Fügt eine neue Zeile (Regal mit 6 Slots) hinzu.", "Adds a new row (shelf with 6 slots)."),
 "Diesen Tab löschen": ("Löscht den ganzen Tab samt Zeilen (nur mit 'Löschen freigeben').", "Deletes the whole tab with its rows (only with 'Allow delete')."),
 "+ Tab": ("Fügt einen neuen Tab (Kategorie im Shop-Fenster) hinzu.", "Adds a new tab (category in the shop window)."),
 "(leer) -": ("Leert den Slot.", "Empties the slot."),
 "Löschen freigeben": ("Sicherung: erst wenn gesetzt, erscheinen Löschen-Knöpfe.", "Safety: delete buttons only appear when this is ticked."),
 # ---- Custom NPC / Mob
 "NPC##kind": ("Einen NPC (Händler, Questgeber ...) erstellen.", "Create an NPC (merchant, quest giver ...)."),
 "Monster##kind": ("Ein Monster erstellen.", "Create a monster."),
 "InxName (eindeutig)": ("Interner Schlüsselname; muss in MobInfo eindeutig sein, keine Leerzeichen.", "Internal key name; must be unique in MobInfo, no spaces."),
 "Anzeigename": ("Name, der im Spiel angezeigt wird.", "Name shown in game."),
 "ID automatisch (erste freie im größten freien Block, in allen Tabellen frei)": ("Vergibt die erste in ALLEN beteiligten Tabellen freie ID im größten freien Bereich.", "Assigns the first ID free in ALL involved tables in the largest free block."),
 "ID": ("ID von Hand festlegen (muss in allen Tabellen frei sein).", "Set the ID by hand (must be free in all tables)."),
 "Level": ("Level des Monsters.", "Level of the monster."),
 "Max. HP": ("Maximale Lebenspunkte.", "Maximum hit points."),
 "Gehtempo": ("Gehgeschwindigkeit.", "Walking speed."),
 "Lauftempo": ("Laufgeschwindigkeit.", "Running speed."),
 "Größe": ("Größe/Skalierung des Modells (1000 = normal).", "Size/scaling of the model (1000 = normal)."),
 "Wie Vorlage": ("Aussehen (Modell/Avatar) der Vorlage übernehmen.", "Take the appearance (model/avatar) from the template."),
 "Anderes Modell": ("Ein anderes vorhandenes Modell (MobViewInfo.FileName) verwenden.", "Use another existing model (MobViewInfo.FileName)."),
 "Spieler-Avatar mit Rüstung": ("NPC sieht wie ein Spieler aus (NPCViewInfo): Klasse, Gesicht, Frisur, Rüstung und Waffen.", "NPC looks like a player (NPCViewInfo): class, face, hair, armor and weapons."),
 "Modell wählen...": ("Modell aus den in MobViewInfo verwendeten wählen.", "Choose a model from those used in MobViewInfo."),
 "Klasse (0-5)": ("0 Fighter, 1 Archer (keine Modelle), 2 Cleric, 3 Mage, 4 Joker, 5 Sentinel.", "0 Fighter, 1 Archer (no models), 2 Cleric, 3 Mage, 4 Joker, 5 Sentinel."),
 "Geschlecht (1=männl., 0=weibl.)": ("Geschlecht des Avatars (1 männlich, 0 weiblich; nach ChrCreateEquip.IsMale vermutet).", "Gender of the avatar (1 male, 0 female; assumed from ChrCreateEquip.IsMale)."),
 "Gesicht": ("Gesichtsform (Face00N.nif der Klasse).", "Face shape (Face00N.nif of the class)."),
 "Frisur": ("Frisur (HairInfo-ID).", "Hairstyle (HairInfo ID)."),
 "Haarfarbe": ("Haarfarbe (Nummer).", "Hair color (number)."),
 "Dialog der Vorlage kopieren (NpcDialogData)": ("Kopiert das Gespräch der Vorlage für den neuen NPC.", "Copies the template's conversation for the new NPC."),
 "Auf der offenen Karte platzieren (World/NPC.txt)": ("Trägt den NPC in World/NPC.txt für die geöffnete Karte ein.", "Enters the NPC in World/NPC.txt for the open map."),
 "Richtung": ("Blickrichtung in Grad.", "Facing direction in degrees."),
 "Kartenmitte": ("Setzt die Position auf die Mitte der Karte.", "Sets the position to the center of the map."),
 "Rolle": ("Aufgabe des NPCs: QuestNpc, Merchant, Guard, NPCMenu, StoreManager, Gate.", "Task of the NPC: QuestNpc, Merchant, Guard, NPCMenu, StoreManager, Gate."),
 "Rollenargument (z.B. Quest, Item, Weapon, Skill)": ("Zusatz zur Rolle, z.B. Merchant + Item/Weapon/WeaponTitle/Skill/Guild.", "Addition to the role, e.g. Merchant + Item/Weapon/WeaponTitle/Skill/Guild."),
 "Anlegen": ("Erzeugt alle Zeilen in allen Tabellen. Danach 'Alle geänderten SHN speichern'.", "Creates all rows in all tables. Then 'Save all changed SHN'."),
 "Alle geänderten SHN speichern": ("Schreibt alle geänderten SHN-Tabellen (Client und Server) auf die Platte.", "Writes all modified SHN tables (client and server) to disk."),
 "...": ("Wert aus der Liste wählen.", "Choose a value from the list."),
 # ---- Höhe
 "Anheben": ("Pinsel hebt das Gelände an.", "Brush raises the terrain."),
 "Absenken": ("Pinsel senkt das Gelände ab.", "Brush lowers the terrain."),
 "Glätten": ("Gleicht die Höhen an die Umgebung an.", "Blends the heights with the surroundings."),
 "Einebnen": ("Setzt das Gelände auf die 'Zielhöhe'.", "Sets the terrain to the 'target height'."),
 "Radius": ("Pinselgröße in Welteinheiten.", "Brush size in world units."),
 "Stärke": ("Wie stark der Pinsel pro Zug wirkt.", "How strongly the brush acts per stroke."),
 "Zielhöhe": ("Höhe, auf die 'Einebnen' das Gelände setzt.", "Height to which 'Flatten' sets the terrain."),
 "Rückgängig (Strg+Z)": ("Nimmt den letzten Höhen-Pinselzug zurück (Strg+Z).", "Reverts the last height brush stroke (Ctrl+Z)."),
 "Wiederholen (Strg+Y)": ("Stellt den zurückgenommenen Pinselzug wieder her (Strg+Y).", "Restores the reverted brush stroke (Ctrl+Y)."),
 # ---- Textur
 "Name##newLayer": ("Name des neuen Layers.", "Name of the new layer."),
 "Diffuse##newLayer": ("Bilddatei (Diffuse-Textur) des neuen Layers.", "Image file (diffuse texture) of the new layer."),
 "Durchsuchen...##tex": ("Bilddatei per Dialog wählen.", "Choose the image file via a dialog."),
 "UV-Scale##newLayer": ("Wie oft sich die Textur über die Karte wiederholt (größer = kleinere Kacheln).", "How often the texture repeats over the map (larger = smaller tiles)."),
 "Layer hinzufügen": ("Legt einen neuen Layer mit diesen Angaben an.", "Creates a new layer with these settings."),
 "Layer entfernen": ("Löscht den gewählten Layer samt seinen Gewichten.", "Deletes the selected layer with its weights."),
 "Erhöhen": ("Pinsel verstärkt den gewählten Layer.", "Brush strengthens the selected layer."),
 "Senken": ("Pinsel schwächt den gewählten Layer.", "Brush weakens the selected layer."),
 "Radius##tex": ("Pinselgröße in Welteinheiten (Textur).", "Brush size in world units (texture)."),
 "Stärke##tex": ("Pinselstärke pro Zug (Textur).", "Brush strength per stroke (texture)."),
 "Rückgängig (Textur)": ("Nimmt den letzten Textur-Pinselzug zurück.", "Reverts the last texture stroke."),
 "Wiederholen (Textur)": ("Stellt den zurückgenommenen Textur-Pinselzug wieder her.", "Restores the reverted texture stroke."),
 # ---- Walk
 "Sperren (blockiert)": ("Pinsel macht Zellen blockiert (nicht begehbar).", "Brush makes cells blocked (not walkable)."),
 "Freigeben (begehbar)": ("Pinsel macht Zellen begehbar.", "Brush makes cells walkable."),
 "Radius##walk": ("Pinselgröße in Welteinheiten (eine Zelle = 6,25).", "Brush size in world units (one cell = 6.25)."),
 "1 Zelle##walk": ("Pinsel trifft nur die Zelle unter dem Zeiger.", "Brush only hits the cell under the pointer."),
 "Grundflächen sichtbarer Objekte SPERREN": ("Sperrt die Zellen unter den Grundflächen aller sichtbaren Objekte (Sichtbarkeit beachten).", "Blocks the cells under the footprints of all visible objects (mind the visibility)."),
 "Grundflächen sichtbarer Objekte FREIGEBEN": ("Gibt die Zellen unter den Grundflächen aller sichtbaren Objekte frei.", "Releases the cells under the footprints of all visible objects."),
 "Rückgängig (Walk)": ("Nimmt die letzte Begehbarkeits-Änderung zurück.", "Reverts the last walkability change."),
 "Wiederholen (Walk)": ("Stellt die zurückgenommene Begehbarkeits-Änderung wieder her.", "Restores the reverted walkability change."),
 # ---- Objekte
 "Platzieren": ("Klick in die 2D-Ansicht setzt ein neues Objekt.", "Click in the 2D view places a new object."),
 "Auswählen": ("Klick in die 2D-Ansicht wählt das nächste Objekt.", "Click in the 2D view selects the nearest object."),
 "Modellpfad": ("Pfad des Modells (NIF), das platziert wird.", "Path of the model (NIF) to place."),
 "Durchsuchen...##nif": ("Modell aus der Bibliothek wählen.", "Choose a model from the library."),
 "Rotation um Hochachse (°)##new": ("Drehung neuer Objekte um die senkrechte Achse in Grad.", "Rotation of new objects around the vertical axis in degrees."),
 "Skalierung##new": ("Größenfaktor neuer Objekte.", "Scale factor of new objects."),
 "Rotation um Hochachse (°)": ("Drehung des gewählten Objekts um die senkrechte Achse in Grad.", "Rotation of the selected object around the vertical axis in degrees."),
 "Skalierung": ("Größenfaktor des gewählten Objekts.", "Scale factor of the selected object."),
 "Objekt löschen": ("Löscht das gewählte Objekt.", "Deletes the selected object."),
 # ---- NPC
 "Coord-X": ("Welt-X-Position (Ost) des NPCs.", "World X position (east) of the NPC."),
 "Coord-Y": ("Welt-Z-Position (Nord) des NPCs (in NPC.txt 'Coord-Y').", "World Z position (north) of the NPC (called 'Coord-Y' in NPC.txt)."),
 "-15": ("Dreht die Blickrichtung um -15 Grad.", "Rotates the facing by -15 degrees."),
 "+15": ("Dreht die Blickrichtung um +15 Grad.", "Rotates the facing by +15 degrees."),
 "+90": ("Dreht die Blickrichtung um +90 Grad.", "Rotates the facing by +90 degrees."),
 "180": ("Dreht die Blickrichtung um 180 Grad.", "Rotates the facing by 180 degrees."),
 "Kamera zu diesem NPC": ("Setzt die 3D-Kamera auf den gewählten NPC.", "Puts the 3D camera on the selected NPC."),
 "Drehsinn": ("Zuordnung Richtung -> Blickwinkel: wie angegeben oder gespiegelt (gilt für alle NPCs).", "Mapping direction -> facing angle: as given or mirrored (applies to all NPCs)."),
 "Blick bei Richtung 0": ("Versatz der Blickrichtung bei Richtung 0 (gilt für alle NPCs). Passt den Pfeil an das Spiel an.", "Offset of the facing at direction 0 (applies to all NPCs). Adjusts the arrow to the game."),
 "Dialog bearbeiten": ("Öffnet den Gesprächseditor (Begrüßung und Knöpfe, NpcDialogData).", "Opens the conversation editor (greeting and buttons, NpcDialogData)."),
 "KI-Skript (Lua) bearbeiten": ("Öffnet das Lua-Verhaltensskript des NPCs.", "Opens the NPC's Lua behaviour script."),
 "Patrouillenroute bearbeiten": ("Öffnet die Wegpunkte, die der NPC abläuft.", "Opens the waypoints the NPC walks along."),
 "Händler-Inventar bearbeiten": ("Öffnet den Shop-Editor (NPCItemList) dieses Händlers.", "Opens the shop editor (NPCItemList) of this merchant."),
 "World/NPC.txt speichern": ("Schreibt alle NPC-Änderungen in World/NPC.txt.", "Writes all NPC changes to World/NPC.txt."),
 # ---- Mobs
 "+ Zone (Kopie der gewählten)": ("Dupliziert die gewählte Spawn-Zone samt ihren Monstern.", "Duplicates the selected spawn zone including its monsters."),
 "Zone samt Monstern löschen": ("Löscht die Zone und alle ihre Monster (nur mit 'Löschen freigeben').", "Deletes the zone and all its monsters (only with 'Allow delete')."),
 "KI": ("Öffnet das Verhaltensskript dieses Monsters.", "Opens the behaviour script of this monster."),
 "Route": ("Öffnet die Wegpunkte (MobRoam) dieses Monsters.", "Opens the waypoints (MobRoam) of this monster."),
 "Monster entfernen": ("Entfernt dieses Monster aus der Zone.", "Removes this monster from the zone."),
 "+ Monster hinzufügen": ("Fügt der Zone ein neues Monster hinzu.", "Adds a new monster to the zone."),
 "MobRegen speichern": ("Schreibt die Spawn-Zonen in die MobRegen-Datei der Karte.", "Writes the spawn zones to the map's MobRegen file."),
 # ---- Ansicht / Sichtbarkeit
 "Sichtbarkeit": ("Blendet Teile der Karte nur in der Anzeige ein/aus - die Daten bleiben unverändert.", "Shows/hides parts of the map in the display only - the data stays unchanged."),
 "Terrain": ("Blendet das Gelände ein/aus.", "Shows/hides the terrain."),
 "Objekt-Modelle (3D)": ("Blendet die 3D-Modelle der Objekte ein/aus.", "Shows/hides the 3D models of objects."),
 "Objekt-Platzhalter (3D)": ("Blendet die Pyramiden für Objekte ohne ladbares Modell ein/aus.", "Shows/hides the pyramids for objects without a loadable model."),
 "NPC-Modelle (3D)": ("Blendet die NPC-Modelle im 3D-Bild ein/aus.", "Shows/hides the NPC models in the 3D image."),
 "NPC-Namen und Blickpfeile (3D, NPC-Modus)": ("Zeigt Namen und Blickpfeile der NPCs im 3D-Bild (nur im NPC-Modus).", "Shows names and facing arrows of NPCs in the 3D image (NPC mode only)."),
 "Objekte im 2D-View": ("Blendet die Objektpunkte in der 2D-Ansicht ein/aus.", "Shows/hides the object dots in the 2D view."),
 "Alle Layer an": ("Zeigt alle Terrain-Layer wieder.", "Shows all terrain layers again."),
 "nur": ("Zeigt nur diese Objekt-Kategorie.", "Shows only this object category."),
 "Alle an": ("Zeigt alle Objekt-Kategorien.", "Shows all object categories."),
 "Alle aus": ("Blendet alle Objekt-Kategorien aus.", "Hides all object categories."),
 "+##zoom2dIn": ("2D-Ansicht vergrößern.", "Zoom the 2D view in."),
 "-##zoom2dOut": ("2D-Ansicht verkleinern.", "Zoom the 2D view out."),
 "1:1##zoom2dFit": ("Ganze Karte anzeigen.", "Show the whole map."),
 "+##zoomIn": ("3D-Ansicht näher heran.", "Move the 3D view closer."),
 "-##zoomOut": ("3D-Ansicht weiter weg.", "Move the 3D view away."),
 "Ordner": ("Ausgabeordner.", "Output folder."),
 "Name": ("Name.", "Name."),
}
# Tooltips zu T()-Schlüsseln (Beschriftung kommt aus der Übersetzungstabelle): "T:<schluessel>"
TIPS.update({
 "T:workspace.wireframe": ("Zeigt das Gelände als Gitternetz (Drahtmodell).", "Shows the terrain as a wire mesh."),
 "T:workspace.centercamera": ("Setzt die 3D-Kamera so, dass die ganze Karte zu sehen ist.", "Puts the 3D camera so that the whole map is visible."),
 "T:workspace.save": ("Speichert die Karte.", "Saves the map."),
 "T:workspace.saveas": ("Speichert die Karte unter neuem Namen/Ordner.", "Saves the map under a new name/folder."),
 "T:workspace.undo": ("Nimmt die letzte Änderung zurück (Strg+Z).", "Reverts the last change (Ctrl+Z)."),
 "T:workspace.redo": ("Stellt die zurückgenommene Änderung wieder her (Strg+Y).", "Restores the reverted change (Ctrl+Y)."),
 "T:nav.back": ("Zurück zur vorherigen Ebene.", "Back to the previous level."),
 "T:mapeditor.newmap": ("Legt eine neue Karte an.", "Creates a new map."),
 "T:mapeditor.openmap": ("Öffnet eine vorhandene Karte.", "Opens an existing map."),
 "T:mapeditor.createmap": ("Erzeugt die neue Karte mit den Angaben.", "Creates the new map with the given settings."),
 "T:mapeditor.cancel": ("Bricht ab.", "Cancels."),
 "T:mapeditor.open": ("Öffnet die gewählte Karte.", "Opens the chosen map."),
 "T:card.start": ("Startet diesen Editor.", "Starts this editor."),
 "T:newproject.createsave": ("Legt das Projekt an und speichert die Einstellungen.", "Creates the project and saves the settings."),
 "T:workspace.tab.heightmap": ("Höhenkarte bearbeiten (Gelände anheben, senken, glätten).", "Edit the heightmap (raise, lower, smooth terrain)."),
 "T:workspace.tab.texturing": ("Texturschichten bemalen.", "Paint texture layers."),
 "T:workspace.tab.blockwalk": ("Begehbarkeit (Zellen sperren/freigeben).", "Walkability (block/release cells)."),
 "T:workspace.tab.objects": ("Objekte (Modelle) platzieren und ausrichten.", "Place and align objects (models)."),
 "T:workspace.tab.npcs": ("NPCs platzieren, ausrichten und konfigurieren.", "Place, align and configure NPCs."),
 "T:workspace.tab.npcai": ("Noch ohne eigene Werkzeuge: KI im NPC-Tab bearbeiten.", "No tools of its own yet: edit AI in the NPC tab."),
 "T:workspace.tab.mobs": ("Monster-Spawn-Zonen bearbeiten.", "Edit monster spawn zones."),
 "T:workspace.tab.mobai": ("Noch ohne eigene Werkzeuge: KI im Mob-Tab bearbeiten.", "No tools of its own yet: edit AI in the mob tab."),
 "T:workspace.tab.portals": ("Schnellreise-Ziele (TownPortal, Schriftrollen) bearbeiten.", "Edit fast-travel targets (TownPortal, scrolls)."),
})

# Widgets mit verstecktem Label ("##...") - Tooltip nach Art und Label
TIPS.update({
 "Checkbox:##a": ("Dieses Ziel ist aktiv (wird von der Quest verwendet).", "This target is active (used by the quest)."),
 "Checkbox:##daily": ("Tägliche Quest: kann jeden Tag wiederholt werden.", "Daily quest: can be repeated every day."),
 "Checkbox:##enable": ("Quest ist aktiviert.", "Quest is enabled."),
 "Checkbox:##v": ("Schalter (an = 1). Erklärung: Mauszeiger über den Feldnamen links.", "Switch (on = 1). Explanation: hover the field name on the left."),
 "Combo:##lang": ("Sprache der Oberfläche, der Tooltips und des Handbuchs.", "Language of the interface, tooltips and manual."),
 "InputInt:##a": ("Zahlenwert.", "Numeric value."),
 "InputInt:##i": ("Item-ID; der Name wird daneben aufgelöst (rot = nicht gefunden).", "Item ID; the name is resolved next to it (red = not found)."),
 "InputInt:##id": ("ID (Mob bzw. Item); der Name wird daneben aufgelöst (rot = nicht gefunden).", "ID (mob or item); the name is resolved next to it (red = not found)."),
 "InputInt:##m": ("Mob-ID (Monster, das den Drop fallen lässt).", "Mob ID (monster that drops the item)."),
 "InputInt:##maxlv": ("Höchstes Charakterlevel für diese Quest.", "Highest character level for this quest."),
 "InputInt:##minlv": ("Niedrigstes Charakterlevel für diese Quest.", "Lowest character level for this quest."),
 "InputInt:##n": ("Anzahl.", "Count."),
 "InputInt:##newmapx": ("Breite der neuen Karte in Höhenpunkten.", "Width of the new map in height points."),
 "InputInt:##newmapy": ("Höhe (Tiefe) der neuen Karte in Höhenpunkten.", "Height (depth) of the new map in height points."),
 "InputInt:##r": ("Rate/Chance (Einheit wie in den Spieldaten).", "Rate/chance (unit as in the game data)."),
 "InputInt:##v": ("Zahlenwert dieses Felds. Beschreibung: Mauszeiger über den Feldnamen links.", "Numeric value of this field. Description: hover the field name on the left."),
 "InputText:##action": ("Aktion bzw. Skript, das beim Klick auf den Knopf ausgeführt wird.", "Action or script executed when the button is clicked."),
 "InputText:##label": ("Beschriftung des Knopfes im Gespräch.", "Label of the button in the conversation."),
 "InputText:##clientfolder": ("Client-Ordner (enthält ressystem, resmap, reschar, resitem ...).", "Client folder (contains ressystem, resmap, reschar, resitem ...)."),
 "InputText:##serverfolder": ("Server-Ordner (enthält 9Data/Shine).", "Server folder (contains 9Data/Shine)."),
 "InputText:##projfolder": ("Ordner, in dem die Projektdatei gespeichert wird.", "Folder in which the project file is saved."),
 "InputText:##projname": ("Name des Projekts.", "Name of the project."),
 "InputText:##newmaplayer": ("Name der ersten Texturschicht der neuen Karte.", "Name of the first texture layer of the new map."),
 "InputText:##newmapname": ("Name der neuen Karte.", "Name of the new map."),
 "InputText:##filter": ("Filtert die Liste nach dem eingegebenen Text.", "Filters the list by the entered text."),
 "InputText:##itemfilter": ("Sucht Items nach Name oder Item-Bezeichnung (InxName).", "Searches items by name or item identifier (InxName)."),
 "InputText:##pickfilter": ("Filtert die Auswahlliste.", "Filters the choice list."),
 "InputText:##questsearch": ("Sucht Quests nach ID oder Text.", "Searches quests by ID or text."),
 "InputText:##ressystemroot": ("Pfad zum Client-Ordner ressystem (enthält NpcDialogData.shn).", "Path to the client folder ressystem (contains NpcDialogData.shn)."),
 "InputText:##shinetextrootmob": ("Pfad zum Server-Ordner 9Data/Shine (enthält MobRegen).", "Path to the server folder 9Data/Shine (contains MobRegen)."),
 "InputText:##shinetextrootnpc": ("Pfad zum Server-Ordner 9Data/Shine (enthält World/NPC.txt).", "Path to the server folder 9Data/Shine (contains World/NPC.txt)."),
 "InputText:##shncell": ("Neuer Wert der gewählten Zelle. Enter oder 'Übernehmen' wendet ihn an.", "New value of the selected cell. Enter or 'Apply' applies it."),
 "InputText:##skillfilter": ("Sucht Skills nach Name, InxName oder ID.", "Searches skills by name, InxName or ID."),
 "InputText:##tplfilter": ("Sucht die Vorlage nach Name oder InxName.", "Searches the template by name or InxName."),
 "InputText:##tshmPath": ("Pfad der eigenen Höhenkarten-Datei (.tshm).", "Path of the own heightmap file (.tshm)."),
 "InputText:##tsobjPath": ("Pfad der eigenen Objekt-Datei (.tsobj).", "Path of the own object file (.tsobj)."),
 "InputText:##tstexPath": ("Pfad der eigenen Textur-Datei (.tstex).", "Path of the own texture file (.tstex)."),
 "InputText:##tswalkPath": ("Pfad der eigenen Begehbarkeits-Datei (.tswalk).", "Path of the own walkability file (.tswalk)."),
 "InputText:##n": ("Name.", "Name."),
 "InputText:##v": ("Wert dieses Felds. Beschreibung: Mauszeiger über den Feldnamen links.", "Value of this field. Description: hover the field name on the left."),
 "InputText:##newmob": ("Name (MobIndex) des Monsters, das der Zone hinzugefügt wird.", "Name (MobIndex) of the monster added to the zone."),
 "SliderFloat:##avyaw": ("Dreht die Avatar-Vorschau.", "Rotates the avatar preview."),
 "SliderInt:##scalepct": ("Prozentwert der Skalierung (100 = unverändert).", "Percentage of the scaling (100 = unchanged)."),
})

# NPC-Ausrichtung (Block&Walk-Schaetzung, CHANGELOG [0.44.34])
TIPS.update({
 "Versatz aus dieser Karte schaetzen (Block&Walk)": ("Testet für alle NPCs dieser Karte, welcher Versatz sie im Schnitt am ehesten von der nächsten Wand weg blicken lässt (Annahme: Rücken zur Wand). Grobe Schätzung.", "For all NPCs on this map, tests which offset most often makes them face away from the nearest wall on average (assumption: back to the wall). A rough estimate."),
 "Versatz bei Richtung 0 (Grad)": ("Versatz der Zuordnung Richtung -> Blickwinkel bei Richtung 0 (gilt für alle NPCs). Per Block&Walk-Analyse auf 0 Grad voreingestellt, hier frei einstellbar.", "Offset of the direction -> facing-angle mapping at direction 0 (applies to all NPCs). Preset to 0 degrees from a Block&Walk analysis, freely adjustable here."),
 "SmallButton:0##offreset": ("Setzt den Versatz auf den Standardwert 0 Grad zurück.", "Resets the offset to the default of 0 degrees."),
})
