#!/usr/bin/env python3
"""Build Aurelia75 v2 from the supplied coastal-citadel visual target.

This is the high-density/reference version of Aurelia.  Every city object is a
real Gamebryo NIF generated by tools/nif/generate_aurelia_landmarks.py.  A real
Fiesta/NextGen map folder can be produced by providing a read-only client (the
verified Rou HTD/HTDG/SHBD are used only as terrain/walk templates).

For renderer/CI evidence, --scene-only writes the exact SHMD, layout JSON and
NIF asset set without requiring a client installation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import struct
import sys
from dataclasses import asdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
NIF_TOOLS = REPO / "tools" / "nif"
for item in (str(HERE), str(NIF_TOOLS)):
    if item not in sys.path:
        sys.path.insert(0, item)

import generate_aurelia_75_125 as base
import generate_aurelia_landmarks as assets

MAP_ID = base.MAP_ID
MAP_TITLE = "Aurelia - Bastion der Morgenwacht / Reference City v2"
ASSET_PREFIX = rf"resmap\field\{MAP_ID}\assets"


def nif(name: str) -> str:
    return ASSET_PREFIX + "\\" + name + ".nif"


HOUSE_A = nif("NG_SmallHouse_A")
HOUSE_B = nif("NG_SmallHouse_B")
STORE = nif("NG_GeneralStore")
STALL = nif("NG_MarketStall")
LAMP = nif("NG_LanternStreetlamp")
TREE = nif("NG_StylizedTree")
PLANTER = nif("NG_FlowerPlanter")
BENCH = nif("NG_Bench")
CRATES = nif("NG_CrateStack")
BARREL = nif("NG_Barrel")
WALL = nif("NG_Aurelia_WallSegment")
TOWER = nif("NG_Aurelia_WatchTower")
GATE = nif("NG_Aurelia_MainGate")
BRIDGE = nif("NG_Aurelia_GrandBridge")
TERRACE = nif("NG_Aurelia_Terrace")
STAIRS = nif("NG_Aurelia_GrandStairs")
FOUNTAIN = nif("NG_Aurelia_GrandFountain")
CATHEDRAL = nif("NG_Aurelia_Cathedral")
PIER = nif("NG_Aurelia_HarborPier")
LIGHTHOUSE = nif("NG_Aurelia_Lighthouse")
WATER = nif("NG_Aurelia_WaterPlane")
COLONNADE = nif("NG_Aurelia_Colonnade")


def A(out, model, x, y, z, yaw=0.0, scale=1.0, collision=None, district="", note=""):
    base.add(out, model, x, y, elevation=z, yaw=yaw, scale=scale,
             collision=collision, district=district, note=note)


def line(out, model, x0, y0, x1, y1, z, spacing, *, yaw=None, scale=1.0,
         collision=None, district="walls", skip=()):
    dx, dy = x1-x0, y1-y0
    length = math.hypot(dx, dy)
    count = max(1, int(round(length / spacing)))
    angle = math.degrees(math.atan2(dy, dx))
    model_yaw = angle if yaw is None else yaw
    for i in range(count + 1):
        t = i / count
        x, y = x0 + dx*t, y0 + dy*t
        if any(math.hypot(x-sx, y-sy) < radius for sx, sy, radius in skip):
            continue
        A(out, model, x, y, z, model_yaw, scale, collision, district)


def ring_positions(cx, cy, rx, ry, count, phase=0.0):
    for i in range(count):
        a = 2*math.pi*i/count + phase
        yield cx + math.cos(a)*rx, cy + math.sin(a)*ry, math.degrees(a) + 90


def build_reference_city() -> list[base.Placement]:
    p: list[base.Placement] = []

    # Sea/horizon geometry used both by the actual map and deterministic evidence renderer.
    A(p, WATER, 9300, 250, 385, scale=1.35, district="harbor", note="south sea basin")

    # ------------------------------------------------------------------
    # Outer fortified city ring: broad white walls, blue-roof towers and four gates.
    # ------------------------------------------------------------------
    south_y, north_y, west_x, east_x = 1850, 4950, 7350, 11250
    wall_z = 500
    line(p, WALL, west_x, south_y, east_x, south_y, wall_z, 575,
         collision=(285, 70), skip=((9300, south_y, 470),))
    line(p, WALL, west_x, north_y, east_x, north_y, 790, 575,
         collision=(285, 70), skip=((9300, north_y, 470),))
    line(p, WALL, west_x, south_y, west_x, north_y, wall_z, 575, yaw=90,
         collision=(70, 285), skip=((west_x, 3300, 470),))
    line(p, WALL, east_x, south_y, east_x, north_y, wall_z, 575, yaw=90,
         collision=(70, 285), skip=((east_x, 3300, 470),))
    for x, y, z in [
        (west_x, south_y, 490), (east_x, south_y, 490),
        (west_x, north_y, 780), (east_x, north_y, 780),
        (8050, south_y, 490), (10550, south_y, 490),
        (west_x, 2650, 520), (west_x, 4100, 690),
        (east_x, 2650, 520), (east_x, 4100, 690),
        (8050, north_y, 780), (10550, north_y, 780),
    ]:
        A(p, TOWER, x, y, z, collision=(175,175), district="walls")
    A(p, GATE, 9300, south_y, 495, 0, 1.05, (520,180), "westtor", "grand harbor gate")
    A(p, GATE, 9300, north_y, 785, 180, 1.05, (520,180), "morgenwacht", "north citadel gate")
    A(p, GATE, west_x, 3300, 575, 90, 0.92, (180,520), "westtor")
    A(p, GATE, east_x, 3300, 575, 90, 0.92, (180,520), "veteranen")

    # East and west monumental access bridges hanging over the cliff line.
    A(p, BRIDGE, 6920, 3300, 470, 90, 1.0, (690,240), "westtor")
    A(p, BRIDGE, 11680, 3300, 470, 90, 1.0, (690,240), "veteranen")

    # ------------------------------------------------------------------
    # Harbor: lighthouse, piers, warehouses, seafront shops and cargo.
    # ------------------------------------------------------------------
    A(p, LIGHTHOUSE, 7600, 850, 390, 0, 1.18, (260,260), "harbor", "western beacon")
    A(p, LIGHTHOUSE, 11000, 1050, 400, 0, 0.92, (240,240), "harbor", "eastern beacon")
    for x in (8200, 8750, 9300, 9850, 10400):
        A(p, PIER, x, 1050, 410, 0, 0.82, (180,600), "harbor")
        A(p, STORE, x, 1650, 485, 180, 0.72, (260,190), "harbor")
        A(p, CRATES, x-170, 1425, 485, (x//50)%180, 0.8, (75,75), "harbor")
        A(p, BARREL, x+165, 1435, 485, 0, 0.85, (40,40), "harbor")

    # ------------------------------------------------------------------
    # Lower city / Kronmarkt: dense radial market around the fountain.
    # ------------------------------------------------------------------
    A(p, TERRACE, 9300, 2920, 500, 0, 1.24, (1000,760), "market", "grand civic terrace")
    A(p, FOUNTAIN, 9300, 2850, 655, 0, 1.10, (470,470), "market", "Aurelia sun fountain")
    for x, y, yaw in ring_positions(9300, 2850, 760, 570, 18, phase=0.10):
        A(p, STALL, x, y, 635, yaw+90, 0.52, (115,70), "market")
    for x, y, yaw in ring_positions(9300, 2850, 1080, 820, 14, phase=0.02):
        A(p, HOUSE_B if int(x+y)%2 else HOUSE_A, x, y, 515, yaw+90, 0.72,
          (190,155), "market")
    for x, y, yaw in ring_positions(9300, 2850, 620, 470, 12, phase=0.22):
        A(p, LAMP, x, y, 640, 0, 0.72, (22,22), "market")
    for x, y, yaw in ring_positions(9300, 2850, 1180, 930, 14, phase=0.18):
        A(p, TREE, x, y, 510, 0, 0.48, (90,90), "market")

    # Main stores define the civic crossroads.
    for x, y, yaw in [(8200,2780,90),(10400,2780,-90),(8400,3500,120),(10200,3500,-120)]:
        A(p, STORE, x, y, 535 if y<3200 else 585, yaw, 0.82, (320,220), "market")

    # ------------------------------------------------------------------
    # Mid terrace / Runenwerk and veteran quarter.
    # ------------------------------------------------------------------
    A(p, TERRACE, 8500, 3800, 590, 0, 1.02, (900,660), "runenwerk")
    A(p, TERRACE, 10100, 3800, 590, 0, 1.02, (900,660), "veteranen")
    A(p, COLONNADE, 8500, 3960, 745, 0, 0.90, (560,180), "runenwerk")
    A(p, COLONNADE, 10100, 3960, 745, 0, 0.90, (560,180), "veteranen")
    for base_x, district in ((8200,"runenwerk"),(9950,"veteranen")):
        for row in range(2):
            for col in range(4):
                x = base_x + col*310
                y = 3400 + row*430
                A(p, HOUSE_B if (row+col)%2 else HOUSE_A, x, y, 580+row*55, 180, 0.62,
                  (165,135), district)
    for x in (7900,8150,10450,10700):
        for y in (3450,3900,4300):
            A(p, TREE, x, y, 590+(y-3450)*0.18, 0, 0.42, (80,80), "gardens")
            A(p, PLANTER, x+90, y+40, 605+(y-3450)*0.18, 90, 0.55, (75,35), "gardens")

    # ------------------------------------------------------------------
    # Monumental ascent. The broad staircase creates the reference-image vertical hierarchy.
    # ------------------------------------------------------------------
    A(p, STAIRS, 9300, 3820, 625, 0, 1.12, (460,900), "morgenwacht", "grand ascent")
    for x in (8750, 9850):
        A(p, COLONNADE, x, 4240, 770, 90 if x<9300 else -90, 0.78, (420,150), "morgenwacht")
        for y in (4060,4400):
            A(p, TREE, x + (-220 if x<9300 else 220), y, 760, 0, 0.46, (85,85), "gardens")

    # ------------------------------------------------------------------
    # Upper citadel: second terrace and dominant cathedral/palace silhouette.
    # ------------------------------------------------------------------
    A(p, TERRACE, 9300, 4620, 820, 0, 1.34, (1100,780), "morgenwacht", "cathedral terrace")
    A(p, CATHEDRAL, 9300, 4680, 970, 0, 1.12, (800,620), "morgenwacht", "Bastion of the Morning Watch")
    for x in (8250, 10350):
        A(p, TOWER, x, 4620, 815, 0, 0.82, (150,150), "morgenwacht")
        A(p, COLONNADE, x, 4490, 805, 0, 0.72, (430,150), "morgenwacht")
    for x, y, yaw in ring_positions(9300, 4590, 1320, 520, 18, phase=0.12):
        A(p, TREE, x, y, 815, yaw, 0.43, (78,78), "gardens")

    # ------------------------------------------------------------------
    # Residential infill: intentionally irregular to avoid a sterile grid.
    # ------------------------------------------------------------------
    residential = [
        (7700,2200,0),(8000,2180,8),(8320,2200,-8),(10700,2200,5),(10380,2180,-8),(10050,2200,6),
        (7700,2550,12),(8000,2520,-4),(10680,2530,-8),(10360,2520,5),
        (7700,3000,4),(7900,3200,-12),(10880,3000,-4),(10680,3200,10),
        (7800,3650,16),(10800,3650,-16),(7850,4100,10),(10750,4100,-10),
    ]
    for i,(x,y,yaw) in enumerate(residential):
        z = 500 + max(0,y-2600)*0.10
        A(p, HOUSE_B if i%3 else HOUSE_A, x, y, z, yaw, 0.68, (175,145), "residential")
        if i % 2 == 0:
            A(p, LAMP, x+180, y-80, z+5, 0, 0.62, (18,18), "residential")

    # Flower-lined processional route from harbor gate to cathedral.
    for y in range(2050, 4501, 250):
        if 2600 <= y <= 3200:
            continue
        z = 510 + max(0, y-3200)*0.13
        for x in (9030, 9570):
            A(p, PLANTER, x, y, z, 90, 0.52, (70,34), "processional")
            A(p, LAMP, x + (-70 if x<9300 else 70), y, z, 0, 0.58, (18,18), "processional")

    # Benches and trees around civic spaces.
    for x,y,yaw in [(8750,2700,90),(9850,2700,-90),(8750,3050,90),(9850,3050,-90),
                    (8650,3320,0),(9950,3320,180),(8700,4450,0),(9900,4450,180)]:
        z = 520 + max(0,y-3200)*0.13
        A(p, BENCH, x,y,z,yaw,0.58,(95,35),"gardens")

    return p


DISTRICTS = [
    {"id":"harbor","name":"Suedhafen","levels":[85,100],"center":[9300,1250]},
    {"id":"market","name":"Kronmarkt","levels":[85,95],"center":[9300,2850]},
    {"id":"runenwerk","name":"Runenwerk","levels":[95,105],"center":[8500,3850]},
    {"id":"veteranen","name":"Veteranenbastion","levels":[105,115],"center":[10100,3850]},
    {"id":"morgenwacht","name":"Morgenwacht","levels":[115,125],"center":[9300,4650]},
]

NPC_ANCHORS = [
    {"role":"questmaster_75_95","position":[8950,2600,650]},
    {"role":"storage","position":[10100,2800,530]},
    {"role":"item_merchant","position":[8250,2800,530]},
    {"role":"blacksmith","position":[8500,3900,740]},
    {"role":"guild_master","position":[10050,3920,740]},
    {"role":"questmaster_95_110","position":[8750,3950,740]},
    {"role":"questmaster_110_125","position":[9300,4300,835]},
    {"role":"portal_master","position":[9300,2100,520]},
]

PORTAL_ANCHORS = [
    {"name":"Harbor South","min_level":90,"position":[9300,1760,500]},
    {"name":"West Road","min_level":75,"position":[7420,3300,575]},
    {"name":"Veteran Road","min_level":105,"position":[11180,3300,575]},
    {"name":"Morgenwacht North","min_level":120,"position":[9300,4870,790]},
]


def output_dir(project_root: Path) -> Path:
    return project_root.resolve() / "Client" / "resmap" / "field" / MAP_ID


def write_walk_grid(source_client: Path, target: Path, placements: list[base.Placement]):
    source = source_client / "resmap" / "field" / "Rou" / "Rou.shbd"
    grid = base.WalkGridTemplate(source.read_bytes())
    grid.set_world_rect(6750, 450, 11850, 5300, False)
    for obj in placements:
        if obj.collision_x > 0 and obj.collision_y > 0:
            grid.set_world_rect(obj.x-obj.collision_x, obj.y-obj.collision_y,
                                obj.x+obj.collision_x, obj.y+obj.collision_y, True)
    target.write_bytes(grid.to_bytes())
    return {"rows":grid.rows,"cols":grid.cols,"cell_size":grid.cell_size,
            "words_per_row":grid.words_per_row}


def sha256(path: Path) -> str:
    h=hashlib.sha256(); h.update(path.read_bytes()); return h.hexdigest()


def write_layout(path: Path, placements: list[base.Placement], *, terrain=None, walk=None):
    data = {
        "map_id": MAP_ID,
        "title": MAP_TITLE,
        "level_range": [75,125],
        "visual_target": "tiered coastal white-stone/royal-blue fantasy citadel",
        "render_truth": "placements reference the same generated NIFs used by the renderer evidence",
        "districts": DISTRICTS,
        "npc_anchors": NPC_ANCHORS,
        "portal_anchors": PORTAL_ANCHORS,
        "safe_spawn": [9300,2350,520],
        "terrain_template": terrain,
        "walk_grid": walk,
        "placements": [asdict(x) for x in placements],
        "dependencies": sorted({x.model for x in placements}),
    }
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")


def generate_scene(output: Path) -> Path:
    if output.exists(): shutil.rmtree(output)
    output.mkdir(parents=True)
    asset_dir = output / "assets"
    assets.generate(asset_dir)
    placements = build_reference_city()
    base.write_shmd(output / f"{MAP_ID}.shmd", placements)
    write_layout(output / f"{MAP_ID}.layout.json", placements)
    print(f"Scene: {len(placements)} placements / {len(assets.ALL_ASSETS)} generated NIF types")
    return output


def normalize_client(path: Path) -> Path:
    path = path.resolve()
    if (path / "Client" / "resmap").is_dir(): path = path / "Client"
    return path


def generate_map(source_client: Path, project_root: Path, force: bool) -> Path:
    client = normalize_client(source_client)
    source_field = client / "resmap" / "field" / "Rou"
    required = [source_field/"Rou.HTD", source_field/"Rou.HTDG", source_field/"Rou.shbd"]
    missing=[str(x) for x in required if not x.is_file()]
    if missing: raise SystemExit("Missing Rou terrain templates:\n  - " + "\n  - ".join(missing))
    out=output_dir(project_root)
    if out.exists():
        if not force: raise SystemExit(f"Output exists: {out}; use --force")
        shutil.rmtree(out)
    out.mkdir(parents=True)
    placements=build_reference_city()
    assets.generate(out/"assets")
    shutil.copyfile(source_field/"Rou.HTD", out/f"{MAP_ID}.HTD")
    shutil.copyfile(source_field/"Rou.HTDG", out/f"{MAP_ID}.HTDG")
    base.write_ini(out/f"{MAP_ID}.ini")
    base.write_shmd(out/f"{MAP_ID}.shmd", placements)
    walk=write_walk_grid(client,out/f"{MAP_ID}.shbd",placements)
    terrain={"map":"Rou","htd_sha256":sha256(source_field/"Rou.HTD"),
             "htdg_sha256":sha256(source_field/"Rou.HTDG"),"world_size":[12800,12800]}
    write_layout(out/f"{MAP_ID}.layout.json",placements,terrain=terrain,walk=walk)
    (out/"README-Aurelia75-v2.txt").write_text(
        f"{MAP_TITLE}\nObjects: {len(placements)}\nGenerated NIF types: {len(assets.ALL_ASSETS)}\n"
        "Open Aurelia75.ini in NextGen-Editor. NPC/portal IDs remain intentionally unbound.\n",
        encoding="utf-8")
    print(f"Generated real map: {out}\nObjects: {len(placements)}")
    return out


def main() -> int:
    ap=argparse.ArgumentParser()
    ap.add_argument("--scene-only",action="store_true")
    ap.add_argument("--output",type=Path,default=Path("build/aurelia-reference-scene"))
    ap.add_argument("--source-client",type=Path)
    ap.add_argument("--project-root",type=Path)
    ap.add_argument("--force",action="store_true")
    args=ap.parse_args()
    if args.scene_only:
        generate_scene(args.output); return 0
    if not args.source_client or not args.project_root:
        ap.error("--source-client and --project-root are required unless --scene-only is used")
    generate_map(args.source_client,args.project_root,args.force)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
